"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require("express");
var tweetController_1 = require("../controller/tweetController");
var router = express.Router();
router.get('/', tweetController_1.default.getTweets);
router.get('/:id', tweetController_1.default.getTweet);
router.post('/', tweetController_1.default.createTweet);
router.put('/:id', tweetController_1.default.updateTweet);
router.delete('/:id', tweetController_1.default.deleteTweet);
exports.default = router;
